name: pd-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - pandas=1.2.4
  - bokeh
  - pylint
  - pytest
  - pip
  - pip:
    - fair>=1.6.4
    - numpy-financial
    - openpyxl
    - units-of-measure>=0.0.1rc2
