name: drawdown
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=3.1.0
  - appnope=0.1.0
  - appscript=1.1.0
  - arrow=0.14.2
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - backcall=0.1.0
  - binaryornot=0.4.4
  - bleach=3.1.0
  - boost-cpp=1.68.0
  - bqplot=0.11.6
  - bzip2=1.0.6
  - ca-certificates=2019.6.16
  - cairo=1.16.0
  - certifi=2019.6.16
  - cffi=1.12.3
  - cfitsio=3.430
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=1.2.1
  - cookiecutter=1.6.0
  - cryptography=2.7
  - curl=7.64.1
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask-core=2.0.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.5.0
  - entrypoints=0.3
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - future=0.17.1
  - gdal=3.0.1
  - geojson=2.4.1
  - geos=3.7.1
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - giflib=5.1.7
  - git=2.22.0
  - git-lfs=2.7.2
  - glib=2.58.3
  - hdf4=4.2.13
  - hdf5=1.10.5
  - httplib2=0.13.0
  - icu=58.2
  - idna=2.8
  - imageio=2.5.0
  - importlib_metadata=0.18
  - ipydatawidgets=4.0.1
  - ipykernel=5.1.1
  - ipyscales=0.3.0
  - ipython=7.6.1
  - ipython_genutils=0.2.0
  - ipyvolume=0.5.2
  - ipywebrtc=0.5.0
  - ipywidgets=7.5.0
  - jedi=0.14.0
  - jinja2=2.10.1
  - jinja2-time=0.2.0
  - jpeg=9c
  - json-c=0.13.1
  - json5=0.8.4
  - jsonschema=3.0.1
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - jupyterlab=1.0.1
  - jupyterlab_server=1.0.0
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.1
  - libcxx=8.0.0
  - libcxxabi=8.0.0
  - libdap4=3.19.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgdal=3.0.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libpq=11.4
  - libsodium=1.0.16
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libxml2=2.9.9
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - matplotlib-base=3.1.1
  - mistune=0.8.4
  - more-itertools=7.1.0
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.3
  - nodejs=11.14.0
  - notebook=5.7.8
  - numpy=1.16.4
  - olefile=0.46
  - openblas=0.3.6
  - openjpeg=2.3.1
  - openssl=1.1.1b
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - parso=0.5.0
  - pcre=8.41
  - perl=5.26.2
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.1.1
  - pixman=0.38.0
  - pluggy=0.12.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.4
  - poyo=0.4.2
  - proj4=6.1.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - psutil=5.6.3
  - ptyprocess=0.6.0
  - py=1.8.0
  - pyasn1=0.4.5
  - pyasn1-modules=0.2.5
  - pycparser=2.19
  - pygments=2.4.2
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.15.2
  - pysocks=1.7.0
  - pytest=5.0.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - pythreejs=2.1.1
  - pytz=2019.1
  - pywavelets=1.0.3
  - pyzmq=18.0.2
  - qgrid=1.1.1
  - qt=5.9.7
  - qtconsole=4.5.1
  - rauth=0.7.3
  - readline=8.0
  - requests=2.22.0
  - rsa=4.0
  - scikit-image=0.15.0
  - scipy=1.3.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - tbb=2018.0.5
  - terminado=0.8.2
  - testpath=0.4.2
  - tiledb=1.5.1
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=6.0.3
  - traitlets=4.3.2
  - traittypes=0.2.1
  - tzcode=2019a
  - urllib3=1.24.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - whichcraft=0.5.2
  - widgetsnbextension=3.5.0
  - xarray=0.12.2
  - xerces-c=3.2.2
  - xlrd=1.2.0
  - xlwings=0.15.8
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.5.1
  - zlib=1.2.11
  - zstd=1.4.0
prefix: /anaconda3/envs/drawdown
