
ScenariosFile: scenario_inputs.json
PDSAdoptionFile: unit_adoption_data/custom_pds_adoption.json
REFAdoptionFile: unit_adoption_data/custom_ref_adoption.json
BaseYear: 2014
StartYear: 2020
EndYear: 2050
TotalArea: 198
TotalAreaAsOfPeriod: 2018
ChangePerPeriod: 0.0
DelayImpactOfProtectionByOneYear: True
DelayRegrowthOfDegradedLandByOneYear: False
RequiredPythonVersionMinimum: 3.9.5
