
ScenariosFile: solution/seafloorprotection/scenario_inputs.json
PDSAdoptionFile: solution/seafloorprotection/unit_adoption_data/custom_pds_adoption.json
REFAdoptionFile: solution/seafloorprotection/unit_adoption_data/custom_ref_adoption.json
BaseYear: 2014
StartYear: 2020
EndYear: 2050
TotalArea: 490
TotalAreaAsOfPeriod: 2014
ChangePerPeriod: 0.0
DelayImpactOfProtectionByOneYear: True
DelayRegrowthOfDegradedLandByOneYear: False
UseAdoptionForCarbonSequestrationCalculation: False
DirectEmissionsAreAnnual : False # Set False for one-time.
RequiredPythonVersionMinimum: 3.9.5
